# Generated by Django 5.1.7 on 2025-07-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리 명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(blank=True, null=True, verbose_name='삭제여부')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='상품명')),
                ('content', models.TextField(verbose_name='상세 설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('count', models.IntegerField(verbose_name='재고')),
                ('image', models.CharField(max_length=255, verbose_name='모델 이미지 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(blank=True, null=True, verbose_name='삭제여부')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='카테고리 아이디')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='상품 이미지 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(blank=True, null=True, verbose_name='삭제여부')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='상품 아이디')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
