# Generated by Django 5.1.7 on 2025-07-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='영상 생성 상태')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='피팅사진 주소')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='피팅영상')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제여부')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitting_results', to='product.product', verbose_name='상품 아이디')),
            ],
            options={
                'db_table': 'fitting_result',
            },
        ),
    ]
