# Generated by Django 5.1.7 on 2025-07-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitting', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingresult',
            name='user_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitting_results', to='user.userimage', verbose_name='사용자 사진 아이디'),
        ),
        migrations.AlterUniqueTogether(
            name='fittingresult',
            unique_together={('user_image', 'product')},
        ),
    ]
