# Generated by Django 5.1.7 on 2025-07-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='한글 포함 가능', max_length=150, unique=True, verbose_name='사용자 이름'),
        ),
    ]
