name: Backend CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'    # 모든 브랜치 PR에도 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Image Tag
        id: set_docker_image_tag
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            DOCKER_IMAGE_TAG="release-${{ github.run_number }}"
          else
            DOCKER_IMAGE_TAG="pr-${{ github.event.pull_request.number }}-${{ github.run_number }}"
          fi
          echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
        run: |
          docker build -t hwnahee/backend:$DOCKER_IMAGE_TAG .
          docker push hwnahee/backend:$DOCKER_IMAGE_TAG
